### ISSUE TITLE
All tasks should have "become: True"

### ISSUE THREAD

**Issue by sprat** [Oefenweb/ansible-hostname#13]
Since the tasks need root access, the tasks should have `become: True`

**Comment by tersmitten** [comment]
Why not set this a playbook level?

**Comment by sprat** [comment]
Two reasons:
- the role should not depend on external conditions to work
- if set at the playbook level, it can cause problems with other roles, or cause other roles to use an admin account instead of a regular user one and mess up things. For example, I was concerned by a `local_action` in another role that could not be done due to the global `become: True` set at the playbook level which applied also to the local machine.

**Comment by stejoo** [comment]
I agree with @tersmitten this can be solved at the playbook level.

By far the majority of roles out there need administrative privileges to perform their tasks. They do not set `become: true` at every task that needs it, but depend on the playbook to do so. That is the convention with Ansible roles. Sometimes their documentation specifies privilege escalation is needed and depend on the user to run the role with the correct privileges.

If you wish to avoid setting `become: yes` globally because it messes up your play, than why not apply privilege escalation on a per role basis? Like this in your playbook:

```
  roles:
    - role: oefenweb.hostname
      become: yes
```

Tags and role specific variables can be added the same way. You can even put that in a single line using the flow notation of the dictionary like so:

```
    - { role: oefenweb.hostname, become: yes, tags: ['common', 'hostname'] }
```
I even added two tags there.

**Comment by tersmitten** [comment]
Thanks for the writeup @stejoo 

I'm closing this as a "won't fix"

**Comment by sprat** [comment]
I don't really agree with your point of view. But I didn't know the "become in role" trick, I can use that at least. Thanks.
